// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChYTODkJwzHFfNEdqxFYWw5e-bY4NIJvg',
    appId: '1:815122867971:web:59f506743caf84215bab36',
    messagingSenderId: '815122867971',
    projectId: 'tracktrip-3283c',
    authDomain: 'tracktrip-3283c.firebaseapp.com',
    storageBucket: 'tracktrip-3283c.firebasestorage.app',
    measurementId: 'G-8RLH6FLK76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGXztCTnl2mw39V3o1t8BCXZgpHu817ME',
    appId: '1:815122867971:android:e7fa24bbd5b6e8865bab36',
    messagingSenderId: '815122867971',
    projectId: 'tracktrip-3283c',
    storageBucket: 'tracktrip-3283c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5pz2J8KL8TDV-nrBs7BFikXaJaEpYBE0',
    appId: '1:815122867971:ios:6b3477bc20b67d075bab36',
    messagingSenderId: '815122867971',
    projectId: 'tracktrip-3283c',
    storageBucket: 'tracktrip-3283c.firebasestorage.app',
    iosBundleId: 'com.example.trackTripp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5pz2J8KL8TDV-nrBs7BFikXaJaEpYBE0',
    appId: '1:815122867971:ios:6b3477bc20b67d075bab36',
    messagingSenderId: '815122867971',
    projectId: 'tracktrip-3283c',
    storageBucket: 'tracktrip-3283c.firebasestorage.app',
    iosBundleId: 'com.example.trackTripp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChYTODkJwzHFfNEdqxFYWw5e-bY4NIJvg',
    appId: '1:815122867971:web:56bebf085d65e6835bab36',
    messagingSenderId: '815122867971',
    projectId: 'tracktrip-3283c',
    authDomain: 'tracktrip-3283c.firebaseapp.com',
    storageBucket: 'tracktrip-3283c.firebasestorage.app',
    measurementId: 'G-7SJD03GKW3',
  );
}
